export interface SeedMember {
  firstName: string;
  lastName: string;
  preferredName?: string;
  rank?: string;
}

export function buildDisplayName(seed: SeedMember): string {
  const first = (seed.preferredName && seed.preferredName.trim()) || seed.firstName.trim();
  const last = seed.lastName.trim();
  return last ? `${first} ${last}` : first;
}

export const DEFAULT_MEMBERS: SeedMember[] = [
  { firstName: 'Hayden', lastName: 'Johnson' },
  { firstName: 'Callum', lastName: 'Ceglinski' },
  { firstName: 'Samuel', lastName: 'Clements', preferredName: 'Sam' },
  { firstName: 'Thomas', lastName: 'Thorek' },
  { firstName: 'Rebecca', lastName: 'Lieschke', preferredName: 'Bec' },
  { firstName: 'Stephen', lastName: 'Axford', preferredName: 'Steve' },
  { firstName: 'Corey', lastName: 'Donaldson', preferredName: 'Corey' },
  { firstName: 'Robin', lastName: 'Allard', preferredName: 'Rob', rank: 'Captain' },
  { firstName: 'Jack', lastName: 'Shelley' },
  { firstName: 'Gregory', lastName: 'Miiller', preferredName: 'Greg', rank: 'Deputy Captain' },
  { firstName: 'Anthony', lastName: 'Payne', preferredName: 'Tony' },
  { firstName: 'James', lastName: 'Van Daele' },
  { firstName: 'Martin', lastName: 'Lark' },
  { firstName: 'Ian', lastName: 'Voerman' },
  { firstName: 'Shaun', lastName: 'Love', rank: 'Deputy Captain' },
  { firstName: 'Sandra', lastName: 'Love', preferredName: 'Sandi', rank: 'Senior Deputy Captain' },
  { firstName: 'Jeremy', lastName: 'Bulkeley' },
  { firstName: 'Johanna', lastName: 'Kain' },
  { firstName: 'Lachlan', lastName: 'Shand' },
  { firstName: 'Damien', lastName: 'Kinnane', preferredName: 'Damien' },
  { firstName: 'Patrick', lastName: 'Love' },
  { firstName: 'Anthony', lastName: 'Vickers' },
  { firstName: 'David', lastName: 'Hopkins', rank: 'Deputy Captain' },
  { firstName: 'Michael', lastName: 'Singer' },
  { firstName: 'Jessica', lastName: 'Love', preferredName: 'Jess' },
  { firstName: 'Angus', lastName: 'Whitford' },
  { firstName: 'Simon', lastName: "O'Dea", preferredName: 'Simon' },
  { firstName: 'Andrew', lastName: 'Fenton', preferredName: 'Drew' },
  { firstName: 'Briony', lastName: 'Morath' },
  { firstName: 'Kynan', lastName: 'Trotter' },
  { firstName: 'Rebecca', lastName: "O'Brien", preferredName: 'Bec' },
  { firstName: 'Jonathan', lastName: 'Kent' },
  { firstName: 'Christopher', lastName: 'Wall', preferredName: 'Chris' },
  { firstName: 'Sarah', lastName: 'Humphries' },
  { firstName: 'Ion', lastName: 'Maher', preferredName: 'Ion' },
  { firstName: 'Stephen', lastName: 'Blair', preferredName: 'Steve' },
  { firstName: 'Daniel', lastName: 'De Bruin', preferredName: 'Dan' },
  { firstName: 'Callum', lastName: 'Mackenzie' },
  { firstName: 'Michaela', lastName: 'Anderson' },
  { firstName: 'Jeffrey', lastName: 'Buckpitt', preferredName: 'Jeff' },
  { firstName: 'William', lastName: 'Waters', preferredName: 'Bill' },
  { firstName: 'David', lastName: 'Cleverly' },
  { firstName: 'Leana', lastName: 'De Bruin' },
  { firstName: 'John', lastName: 'Curran' },
  { firstName: 'Mary-Anne', lastName: 'Curran' },
  { firstName: 'Richard', lastName: 'Stanford' },
  { firstName: 'Matthew', lastName: 'Stanton', preferredName: 'Matt' },
  { firstName: 'Matthew', lastName: 'Shea' },
  { firstName: 'Ava', lastName: 'Merriman' },
  { firstName: 'Samantha', lastName: 'Foster', preferredName: 'Sam' },
  { firstName: 'Christopher', lastName: 'Knights' },
  { firstName: 'Wade', lastName: 'Cooper', preferredName: 'WG' },
  { firstName: 'Matthew', lastName: 'Tognolini', preferredName: 'Matt' },
  { firstName: 'Richard', lastName: 'Ward' },
  { firstName: 'Ellie', lastName: 'Meggitt' },
  { firstName: 'Alec', lastName: 'McDonnell Millbank' },
  { firstName: 'Alicia', lastName: 'Harris' },
  { firstName: 'Barham', lastName: 'Ferguson' },
  { firstName: 'Adam', lastName: 'Cox' },
  { firstName: 'Lachlan', lastName: 'Niven', preferredName: 'Lachie' },
  { firstName: 'Cameron', lastName: 'McAlister' },
  { firstName: 'Grant', lastName: 'Mills' },
  { firstName: 'Emma', lastName: 'Gwynn' },
  { firstName: 'Mark', lastName: 'Gwynn' },
  { firstName: 'Myles Anthony Frazer', lastName: 'Duke' },
  { firstName: 'Matthew', lastName: 'Hayward-Wright', preferredName: 'Matt' },
  { firstName: 'Nikhil', lastName: 'Narayan' },
  { firstName: 'Clara', lastName: 'Wilkins' },
  { firstName: 'Maximilian', lastName: 'de Kantzow', preferredName: 'Max' },
  { firstName: 'Edwin', lastName: 'Casey Dobinson', preferredName: 'Eddie' },
  { firstName: 'Max', lastName: 'West-newman' },
  { firstName: 'Glen', lastName: 'Bishop' },
  { firstName: 'Emma', lastName: 'Perkins' },
  { firstName: 'Jarra', lastName: 'Robinson' },
  { firstName: 'Duncan', lastName: 'Campbell-Wilson' },
  { firstName: 'Beverly', lastName: 'Campbell-Wilson' },
  { firstName: 'Alison', lastName: 'Inskeep', preferredName: 'Ali' },
  { firstName: 'David', lastName: 'Inskeep' },
  { firstName: 'Barry', lastName: 'Mcroberts' },
  { firstName: 'Douglas', lastName: 'Palmer', preferredName: 'Doug', rank: 'Deputy Captain' },
  { firstName: 'Sheldon', lastName: 'Williams' },
  { firstName: 'Deryck', lastName: 'Clarke' },
  { firstName: 'Stewart', lastName: 'Wilson' },
  { firstName: 'Paul', lastName: 'Davis' },
  { firstName: 'Andrew', lastName: 'Donaldson', preferredName: 'Andy', rank: 'Deputy Captain' },
  { firstName: 'Michael', lastName: 'Fitzgerald', preferredName: 'Mick' },
  { firstName: 'Heather', lastName: 'Hubbard' },
  { firstName: 'Rebecca', lastName: 'Morris' },
  { firstName: 'Peter', lastName: 'Morris', preferredName: 'Pete' },
  { firstName: 'Mark', lastName: 'Thorek' },
  { firstName: 'Richard', lastName: 'Burgoyne-Thorek', rank: 'Deputy Captain' },
  { firstName: 'Alexandra', lastName: 'Campbell-Wilson', preferredName: 'Alex' },
  { firstName: 'Danielle', lastName: 'Clements' },
  { firstName: 'David', lastName: 'Temby' },
  { firstName: 'Kenneth', lastName: 'King' },
  { firstName: 'Darcy', lastName: 'Green' },
  { firstName: 'Glenn', lastName: 'Nelson', rank: 'Deputy Captain' },
  { firstName: 'Patrick', lastName: 'Temby', preferredName: 'Pat' },
  { firstName: 'Catherine', lastName: 'Temby' },
  { firstName: 'Rob', lastName: 'Bolitho' },
  { firstName: 'Carol', lastName: 'Goodwin' },
  { firstName: 'Michael', lastName: 'Uren', preferredName: 'Mick' },
  { firstName: 'Douglas', lastName: 'Gray' },
  { firstName: 'Rebekah', lastName: 'King' },
  { firstName: 'Luke', lastName: 'Donaldson' },
];
